# Learning variables
NUM_EPISODES = 200
LEARN = False
LOAD = False
START_LEVEL = 1

# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Platformer"
NUMBER_OF_LEVELS = 3

# Constants used to scale our sprites from their original size
CHARACTER_SCALING = 1
TILE_SCALING = 1
COIN_SCALING = 1
SPRITE_PIXEL_SIZE = 64
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

# Player constants
PLAYER_MOVEMENT_SPEED = 0
PLAYER_MOVEMENT_SPEED_MAX = 6.5
PLAYER_MOVEMENT_ACCELERATION = 0.25
PLAYER_MOVEMENT_SLOWDOWN = 1.5
GRAVITY = 1
PLAYER_JUMP_SPEED = 20

# RL constants
NUMBER_OF_ACTIONS = 5


# Player starting position
PLAYER_START_X = 128.0
PLAYER_START_Y = 225.0

RIGHT_FACING = 0
LEFT_FACING = 1

# Layer Names from our TileMap
LAYER_NAME_PLATFORMS = "Platformy"
LAYER_NAME_COINS = "Monety"
LAYER_NAME_DONT_TOUCH = "Kolce"
LAYER_NAME_PLAYER = "Player"
LAYER_NAME_ENEMIES = "Przeciwnicy"
LAYER_NAME_BULLETS = "Bullets"

# shooting
SHOOT_SPEED = 15
BULLET_SPEED = 20
BULLET_DAMAGE = 25

# reseting
RESET_TIME = 4
MAX_ITERATIONS = 1000
